
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuynkjsumbjsfmyoypjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1eW5ranN1bWJqc2ZteW95cGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjAyMDEsImV4cCI6MjA1OTA5NjIwMX0.XSX60ip9KzpN8Yzzy7om0l4YarZxPUkKJC3ggFTBTwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    detectSessionInUrl: true,
  },
});
